# Generated by Django 4.0.5 on 2022-06-08 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeNews', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainPage', models.BooleanField(blank=True, null=True)),
                ('mainNews', models.BooleanField(blank=True, null=True)),
                ('mainEvent', models.BooleanField(blank=True, null=True)),
                ('header', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('photoForSlaider', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/slaider/')),
                ('textSlaider', models.CharField(blank=True, max_length=255, null=True)),
                ('shortText', models.TextField(blank=True, null=True)),
                ('longText', models.TextField(blank=True, null=True)),
                ('teg', models.TextField(blank=True, null=True)),
                ('placeEvent', models.TextField(blank=True, null=True)),
                ('hidden', models.BooleanField(blank=True, null=True)),
                ('datetime', models.DateField(blank=True, null=True)),
                ('typeNews', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='websitestrategy.typenews')),
            ],
        ),
    ]
