# Generated by Django 4.0.5 on 2022-06-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websitestrategy', '0002_tag_remove_news_teg_news_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Tags',
        ),
    ]
